name: Odoo Attendance Automation (Hardcoded Test)

on:
  schedule:
    - cron: '30 7 * * 1-5'   # Check-in at 12:30 PM PKT (UTC 07:30)
    - cron: '40 7 * * 1-5'   # Check-out at 12:40 PM PKT (UTC 07:40)
  workflow_dispatch:        # Allow manual run for testing

jobs:
  check_attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ ! -e /usr/bin/chromedriver ]; then
            sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          fi

      - name: Decide Action
        id: action_type
        run: |
          HOUR=$(date -u +'%H')
          MIN=$(date -u +'%M')
          if [ "$HOUR" -eq 7 ] && [ "$MIN" -ge 30 ] && [ "$MIN" -le 32 ]; then
            echo "action=checkin" >> $GITHUB_OUTPUT
          elif [ "$HOUR" -eq 7 ] && [ "$MIN" -ge 40 ] && [ "$MIN" -le 42 ]; then
            echo "action=checkout" >> $GITHUB_OUTPUT
          else
            echo "action=skip" >> $GITHUB_OUTPUT
          fi

      - name: Run Script
        if: steps.action_type.outputs.action != 'skip'
        env:
          ODOO_EMAIL: harrymax042@gmail.com
          ODOO_PASSWORD: Dev.hamza45@
        run: |
          echo "⏳ Random delay before action..."
          python3 -c "import random, time; delay=random.randint(0, 120); print(f'Delaying {delay} seconds...'); time.sleep(delay)"
          python auto_attendance.py ${{ steps.action_type.outputs.action }}