name: Odoo Attendance Automation (Hardcoded Test)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 9 * * 1-5'   # 2:30 PM PKT (check-in)
    - cron: '35 9 * * 1-5'   # 2:35 PM PKT (check-out)
  workflow_dispatch:        # Allow manual run for testing

jobs:
  check_attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Decide Action
        id: action_type
        run: |
          HOUR=$(date -u +'%H')
          MIN=$(date -u +'%M')
          if [ "$HOUR" -eq 8 ] && [ "$MIN" -ge 0 ] && [ "$MIN" -le 12 ]; then
            echo "action=checkin" >> $GITHUB_OUTPUT
          elif [ "$HOUR" -eq 8 ] && [ "$MIN" -ge 15 ] && [ "$MIN" -le 22 ]; then
            echo "action=checkout" >> $GITHUB_OUTPUT
          else
            echo "action=skip" >> $GITHUB_OUTPUT
          fi

      - name: Run Script
        if: steps.action_type.outputs.action != 'skip'
        env:
          ODOO_EMAIL: harrymax042@gmail.com
          ODOO_PASSWORD: Dev.hamza45@
        run: |
          echo "⏳ Random delay before action..."
          python3 -c "import random, time; delay=random.randint(0, 120); print(f'Delaying {delay} seconds...'); time.sleep(delay)"
          python auto_attendance.py ${{ steps.action_type.outputs.action }}
